OPENAI_API_KEY="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"
COHERE_API_KEY="O1fRcillB48DKa4eNVjvLASWriVb1JWTZyJqlfBn"
FPL_TEAM_ID="1437677"